version: '3'
services:
  lex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '8080:8080'
  nlp:
    build:
      context: ./nlp_api
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
